name: Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Node ${{ matrix.node }} test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2-beta
        with:
          node-version: ">=14.14.0"
      - name: Setup pnpm
        uses: pnpm/action-setup@v1.2.0
        with:
          version: latest
      - run: pnpm i --frozen-lockfile
      - run: pnpm build
      - run: pnpm test
